import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { api } from '../api';

function Home() {
  const [stats, setStats] = useState({ users: 0, projects: 0, posts: 0, comments: 0, requests: 0 });
  const [error, setError] = useState('');

  useEffect(() => {
    async function loadCounts() {
      try {
        const [users, projects, posts, comments, requests] = await Promise.all([
          api.users.list(),
          api.projects.list(),
          api.posts.list(),
          api.comments.list(),
          api.collaboration.list(),
        ]);

        setStats({
          users: users.length,
          projects: projects.length,
          posts: posts.length,
          comments: comments.length,
          requests: requests.length,
        });
      } catch (err) {
        setError(err.message || 'Unable to load dashboard metrics');
      }
    }

    loadCounts();
  }, []);

  return (
    <section className="page-shell">
      <div className="hero-panel">
        <div>
          <p className="eyebrow">Mzansi Builds</p>
          <h1>Green, clean project collaboration</h1>
          <p className="intro">
            A dashboard for users, projects, posts, comments and collaboration requests.
            Connect all backend workflows in one modern React dashboard.
          </p>
        </div>
        <div className="hero-actions">
          <Link className="primary-button" to="/projects">
            Browse projects
          </Link>
          <Link className="outline-button" to="/login">
            Login
          </Link>
        </div>
      </div>

      {error ? <div className="alert error">{error}</div> : null}

      <div className="stats-grid">
        <article className="stat-card">
          <span>Users</span>
          <strong>{stats.users}</strong>
        </article>
        <article className="stat-card">
          <span>Projects</span>
          <strong>{stats.projects}</strong>
        </article>
        <article className="stat-card">
          <span>Posts</span>
          <strong>{stats.posts}</strong>
        </article>
        <article className="stat-card">
          <span>Comments</span>
          <strong>{stats.comments}</strong>
        </article>
        <article className="stat-card">
          <span>Requests</span>
          <strong>{stats.requests}</strong>
        </article>
      </div>

      <div className="panel-row">
        <div className="panel">
          <h2>Administration</h2>
          <p>Manage team members, create projects and track collaboration workflows from one interface.</p>
          <ul>
            <li>Register new users</li>
            <li>Create and update projects</li>
            <li>Approve collaboration requests</li>
          </ul>
        </div>
        <div className="panel">
          <h2>Real-time content</h2>
          <p>View posts and comments generated by your teams to keep project discussions transparent.</p>
          <Link className="text-link" to="/posts">
            View all posts
          </Link>
        </div>
        <div className="panel">
          <h2>Celebration Wall</h2>
          <p>Showcase completed projects and celebrate the achievements of the community.</p>
          <Link className="text-link" to="/celebration">
            View completed projects
          </Link>
        </div>
      </div>
    </section>
  );
}

export default Home;
